# Generated by Django 5.2.5 on 2025-08-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestTourn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='MyBestTourn.team'),
        ),
    ]
