# Generated by Django 5.2.5 on 2025-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBestTourn', '0002_rename_first_name_tournament_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
